- ecoli/library/pymunk_multibody.py
- ecoli/processes/chemotaxis/flagella_motor.py
- ecoli/processes/chromosome_replication.py
- ecoli/processes/environment/multibody_physics.py
This ensures that jitter force calculations are performed using a Numpy PRNG that can be seeded. This also updates `chromosome_replication.py` and `flagella_motor.py` to use the deterministic `create_unique_indexes` method in `schema.py`. Simulations should now be repeatable (tested locally up to 3500 seconds, which includes one round of division).
> Make simulations deterministic

- .github/workflows/pytest.yml
- .github/workflows/pytest_master.yml
- ecoli/library/cell_wall/hole_detection.py
Our pytest times have recently begun to balloon out of control. This PR adds a flag to report the time spent in the most time-consuming tests and skips an unnecessary runtime comparison.
> Add top test times to pytest report

- README.md
- reconstruction/ecoli/flat/metabolic_reactions_removed.tsv
Some EcoCyc reactions have the same metabolite on both sides, resulting in duplicate dict keys when we parse them with reconstruction.spreadsheets.JsonReader._decode_row. One example is https://ecocyc.org/ECOLI/NEW-IMAGE?object=RXN-12440. 
The model can use them to "cheat" since they're not mass balanced, thereby constituting a mass/carbon generating reaction. 
Ideally we'd create some test to see if all reactions are mass balanced at the end, but this'll do for now.
> Reaction patch to remove incorrectly parsed reactions

- reconstruction/ecoli/fit_sim_data_1.py
Added additional ParCa info for the expressionConverge function in fit_sim_data_1.py. Increased iteration cap from 100 to 300, which seems to solve problems with occassional slow convergence for certain cases on my laptop. Usually converges in 3-5 steps, but sometimes will take >100.
> Increase iteration cap for expressionConverge, add more informative print statements

- ecoli/library/initial_conditions.py
This fixes an issue where the `active_replisome` store does not have the expected datatype on sim initialization when the number of initial replisomes is 0.
> Create empty array when zero initial replisomes

- setup.py
Updated setup.py to consolidate Cython extension builds and address compilation errors related to deprecated NumPy API usage. The change silences warnings and ensures compatibility, resolving issues encountered during `make clean compile`.
> setup.py use cython with NPY_NO_DEPRECATED_API

- .github/workflows/pr_tests.yml
- doc/workflows.rst
- ecoli/analysis/multigeneration/new_gene_counts.py
- ecoli/composites/ecoli_configs/cloud.json
- ecoli/composites/ecoli_configs/new_cloud.json
- ecoli/composites/ecoli_configs/run_parca.json
- ecoli/composites/ecoli_configs/test.json
- ecoli/composites/ecoli_configs/test_installation.json
- ecoli/composites/ecoli_configs/two_generations.json
- ecoli/experiments/ecoli_engine_process.py
- ecoli/experiments/ecoli_master_sim.py
- ecoli/experiments/tet_amp_sim.py
- runscripts/analysis.py
- runscripts/create_variants.py
- runscripts/jenkins/configs/ecoli-anaerobic.json
- runscripts/jenkins/configs/ecoli-glucose-minimal.json
- runscripts/jenkins/configs/ecoli-new-gene-gfp.json
- runscripts/jenkins/configs/ecoli-no-growth-rate-control.json
- runscripts/jenkins/configs/ecoli-no-operons.json
- runscripts/jenkins/configs/ecoli-superhelical-density.json
- runscripts/jenkins/configs/ecoli-with-aa.json
- runscripts/nextflow/config.template
- runscripts/parca.py
- runscripts/workflow.py
Users can now specify the ``sim_data_path`` top-level config JSON option to skip the ParCa when running a workflow.
This PR also fixes bugs with the ``emitter_arg`` config option.
> Option to Skip ParCa in Workflows

- doc/workflows.rst
- ecoli/composites/ecoli_configs/default.json
- ecoli/experiments/ecoli_master_sim.py
- ecoli/experiments/tet_amp_sim.py
- runscripts/create_variants.py
This is most useful when running many batches of simulations using the same variant function. In these cases, the baseline lineage(s) will always lead to the same simulation outputs (wasted computation).
> Option to skip baseline variant sim_data

- doc/workflows.rst
- ecoli/library/initial_conditions.py
- ecoli/library/parquet_emitter.py
- reconstruction/ecoli/dataclasses/process/complexation.py
- runscripts/container/build-runtime.sh
- runscripts/container/build-wcm.sh
- runscripts/container/cloud_build.json
- runscripts/container/runtime/Dockerfile
- runscripts/container/wholecell/Dockerfile
- runscripts/nextflow/analysis.nf
- runscripts/nextflow/colony.nf
- runscripts/nextflow/config.template
- runscripts/nextflow/sim.nf
- runscripts/nextflow/template.nf
- runscripts/workflow.py
- wholecell/tests/utils/test_mc_complexation.py
- wholecell/utils/polymerize.py
- If Cython modules are missing, raise error message telling user to run `make clean compile`
- Document that two config JSONs are required to run ParCa and simulation manually (outside a workflow). This forces the user to be explicit about the `sim_data_path` used by the simulation, reducing the chance of using the wrong simulation data.
- Tell Nextflow to move all analysis output to [final output directory structure](https://covertlab.github.io/vEcoli/workflows.html#id9). Also, create copies of ParCa output and simulation data variants in their final output folders. This allows users to safely delete the entire `nextflow_workdirs` directory without losing any of the key simulation outputs.
- Add minimal documentation for troubleshooting Nextflow workflows
- Fix bug with unified Parquet …
> More bug fixes

- runscripts/jenkins/setup-environment.sh
I added a copy of the nextflow binary to `$GROUP_HOME/pyenv/bin`. This allows us to manually update nextflow for bug fixes and new features immediately instead of waiting for Sherlock maintainers to update the nextflow module.
> Use personal nextflow installation instead of module

- runscripts/jenkins/configs/ecoli-anaerobic.json
- runscripts/jenkins/configs/ecoli-glucose-minimal.json
- runscripts/jenkins/configs/ecoli-new-gene-gfp.json
- runscripts/jenkins/configs/ecoli-no-growth-rate-control.json
- runscripts/jenkins/configs/ecoli-no-operons.json
- runscripts/jenkins/configs/ecoli-superhelical-density.json
- runscripts/jenkins/configs/ecoli-with-aa.json
This allows us to test that the workflow pipeline (`runscripts/workflow.py`) works properly on Sherlock and means we can keep the resource requirements of the long-running Jenkins job to a minimum. One core should be enough to `git pull` the latest changes, set up the environment, and launch the Nextflow orchestrator which will submit ParCa/sim/analysis jobs to the cluster.
> Use nextflow to distribute Jenkins CI over Sherlock nodes

- ecoli/experiments/ecoli_master_sim.py
- runscripts/workflow.py
Better automatic date/time experiment ID suffix that should be more friendly for filenames (no special characters/spaces).
> Filename-friendly time suffix

- doc/experiments.rst
- ecoli/experiments/ecoli_master_sim.py
- ecoli/processes/polypeptide_elongation.py
- runscripts/jenkins/configs/ecoli-anaerobic.json
- runscripts/jenkins/configs/ecoli-glucose-minimal.json
- runscripts/jenkins/configs/ecoli-new-gene-gfp.json
- runscripts/jenkins/configs/ecoli-no-growth-rate-control.json
- runscripts/jenkins/configs/ecoli-no-operons.json
- runscripts/jenkins/configs/ecoli-superhelical-density.json
- runscripts/jenkins/configs/ecoli-with-aa.json
- runscripts/workflow.py
Special characters and spaces in the experiment ID completely messes up the directory structure. Better just to disallow them.
> Do not allow special characters in experiment ID

- runscripts/nextflow/config.template
The conservative SLURM executor options that I set to avoid sporadic job submission errors in #230 lead to large periods of downtime where a job has finished but Nextflow has not recognized it as such. This PR attempts to tweak those options to reduce downtime while still avoiding those errors.
> Tweak SLURM executor options to try to minimize downtime

- ecoli/analysis/multigeneration/new_gene_counts.py
- ecoli/analysis/single/mass_fraction_summary.py
- requirements.txt
- runscripts/container/build-runtime.sh
The pytest CI error will be fixed with a new release of `vivarium-core` (see vivarium-collective/vivarium-core#241).
> Address CI failures

- doc/workflows.rst
- ecoli/analysis/multigeneration/new_gene_counts.py
- ecoli/analysis/single/mass_fraction_summary.py
- ecoli/processes/chromosome_structure.py
- runscripts/jenkins/configs/ecoli-anaerobic.json
- runscripts/jenkins/configs/ecoli-glucose-minimal.json
- runscripts/jenkins/configs/ecoli-new-gene-gfp.json
- runscripts/jenkins/configs/ecoli-no-growth-rate-control.json
- runscripts/jenkins/configs/ecoli-no-operons.json
- runscripts/jenkins/configs/ecoli-superhelical-density.json
- runscripts/jenkins/configs/ecoli-with-aa.json
- runscripts/nextflow/analysis.nf
- runscripts/nextflow/config.template
- runscripts/nextflow/template.nf
- runscripts/workflow.py
When running workflows on Sherlock, the Nextflow process that orchestrates the workflow is submitted to SLURM as a long-running, 1 CPU job that stays alive for the duration of the workflow. It is responsible for submitting additional jobs to SLURM for each task in the workflow. Those tasks must wait in the SLURM queue until a node frees up. All the while, the Nextflow job remains mostly idle. This PR fills this idle CPU time by running certain short workflow tasks (build runtime image, analyses, create variants) directly on the same job as the Nextflow orchestrator, simultaneously avoiding the wait that currently comes with submitting those tasks to the SLURM queue (~15 minute average). I found that after including queue wait time, the ParCa takes about the same time to finish whether it …
> Sherlock optimizations

- doc/ci.rst
- doc/workflows.rst
- ecoli/composites/ecoli_master_tests.py
- ecoli/experiments/ecoli_engine_process.py
- ecoli/experiments/ecoli_master_sim.py
- ecoli/library/schema.py
- ecoli/processes/chromosome_structure.py
- ecoli/processes/engine_process.py
- ecoli/processes/rna_interference.py
- ecoli/processes/transcript_elongation.py
- ecoli/processes/unique_update.py
- reconstruction/ecoli/dataclasses/process/rna_decay.py
- runscripts/container/runtime/Dockerfile
- runscripts/container/runtime/Singularity
This modifies `ChromosomeStructure` to remove instead of keep unique molecules at the same genomic coordinates as active replisomes. This makes physical sense because two large proteins cannot occupy the same spot on the chromosome.
Additionally, it fixes an issue I discovered by accident while setting up a Jenkins test for the superhelical density feature. Here's what I think is happening:
1. Say at time `t`, an RNA polymerase (RNAP) `r` is at the same genomic coordinate as an active replisome `a` which has a counterpart `a*` on the other side of the origin of replication, all on chromosome domain 1 (diagram adapted from [this paper](https://doi.org/10.3389/fmicb.2018.02819)). For simplicity, assign coordinates to each genomic location with the origin of replication (oriC) as 0, …
> Remove molecules at same coordinates as replisomes

- .pre-commit-config.yaml
- README.md
- doc/stores.rst
- doc/workflows.rst
- ecoli/library/initial_conditions.py
- ecoli/library/schema.py
- ecoli/processes/chromosome_structure.py
- migration/migration_utils.py
- pyproject.toml
- runscripts/nextflow/analysis.nf
- runscripts/nextflow/template.nf
- runscripts/workflow.py
- uv.lock
If a replisome is unexpectedly removed from the simulation, the superhelical density calculation will fail (see gh-268). While our simulation does not allow this to happen, it can happen in real cells (see https://doi.org/10.1016/S0968-0004(00)01565-6), so I figured I might as well try to tackle the issue.
My solution was to always assume that the now bare replication fork is located at the last recorded location for a removed replisome. For now, I also assume that the bare fork acts like a regular one, treating it as a stationary boundary for superhelical density calculations. In the future, we could introduce more dynamic models of replication fork collapse that include things like dsDNA breaks and replication restart. At that time, we could replace the placeholder indices for removed …
> Handle removed replisomes in superhelical density calculations

- .env
- .github/workflows/pr_tests.yml
- .github/workflows/pytest.yml
- README.md
- doc/docs.rst
- doc/workflows.rst
- ecoli/__init__.py
- ecoli/composites/ecoli_master.py
- ecoli/composites/ecoli_master_tests.py
- ecoli/composites/environment/lattice.py
- ecoli/experiments/antibiotics_tests.py
- ecoli/processes/environment/diffusion_field.py
- ecoli/processes/environment/lysis.py
- ecoli/processes/environment/multibody_physics.py
- ecoli/processes/environment/reaction_diffusion_field.py
- ecoli/processes/enzyme_kinetics.py
- ecoli/processes/listeners/monomer_counts.py
- migration/__init__.py
- reconstruction/__init__.py
- runscripts/__init__.py
- runscripts/container/interactive.sh
- runscripts/container/wholecell/Dockerfile
- validation/__init__.py
- wholecell/__init__.py
- wholecell/tests/utils/test_memory_debug.py
We have always set environment variables to force BLAS/LAPACK to use 1 thread for performance and reproducibility reasons. Instead of having users do this manually with `export ...` or `uv run --env-file .env`, we can do it programmatically in the `__init__.py` files of all modules.
The other tweak automatically installs the vEcoli package for interactive containers on Sherlock. This means users no longer have to manually set the `PYTHONPATH` and guarantees that the required Cython modules are compiled.
> Minor quality of life improvements

- .github/workflows/docs_deploy.yml
- .github/workflows/docs_test.yml
- .github/workflows/pr_tests.yml
- .github/workflows/pytest.yml
- README.md
- runscripts/container/runtime/Dockerfile
- runscripts/container/runtime/Singularity
- runscripts/container/wholecell/Dockerfile
Recent versions of uv no longer require the `CC` environment variable to be manually set for non-Clang C compilers. This results in a simpler and more robust setup process.
> uv 0.5.21 no longer requires explicit CC

- ecoli/composites/ecoli_master.py
- ecoli/composites/ecoli_master_tests.py
`MarkDPeriod` is supposed to update the `has_triggered_division` attribute of a full chromosome when it triggers division, preventing it from triggering division again. This was not happening because I forgot to include a `UniqueUpdate` step after `MarkDPeriod`.
This is really bad as it means that division will happen as soon as a cell has 2 complete chromosomes, skipping the D period. I only discovered this bug because some anaerobic simulations were reaching division with more than 2 full chromosomes, spawning at least one daughter cell that would immediately try to divide again.
> [Critical Bug] Update has_triggered_division before division

- .github/dependabot.yml
Configure Dependabot to only create PRs for security updates.
> Dependabot only for security updates

- runscripts/jenkins/Jenkinsfile/anaerobic
- runscripts/jenkins/Jenkinsfile/glucose
- runscripts/jenkins/Jenkinsfile/optional
- runscripts/jenkins/Jenkinsfile/with_aas
- runscripts/workflow.py
Include the Jenkins CI pipelines in the repo. This improves transparency and also lets me use GitHub App-based authentication instead of a machine account, improving security.
Also, start test different random seeds each time we run a Jenkins workflow.
> Add Jenkinsfiles

- runscripts/workflow.py
Fix oversight where data from log file would only be forwarded to the main process stdout one line at a time.
> Print all log lines as soon as available

- .github/workflows/pr_tests.yml
One of the simulations in this GitHub Action test for simulation reproducibility is started in the background (using `&`). Occasionally, this simulation does not finish writing its output files before the next command runs to compare simulation outputs. Bringing this simulation back to the foreground allows it to finish before running any other commands.
> Make sure both simulations finish before comparing outputs

- .github/workflows/pr_tests.yml
- runscripts/jenkins/Jenkinsfile/anaerobic
- runscripts/jenkins/Jenkinsfile/glucose
- runscripts/jenkins/Jenkinsfile/optional
- runscripts/jenkins/Jenkinsfile/with_aas
Add logic to match previous behavior of Jenkins Slack notifications:
- Only notify for unsuccessful jobs and when they return back to normal
- Remove redundant emoji
- Use hyperlink instead of full URL
Also, fix a new issue I introduced in #289 of `fg` raising an error if the background simulation in our GitHub Actions reproducibility test has already completed. This PR adds new logic to wait for the background simulation that should be more robust.
> Jenkins Slack notifications only for unsuccessful runs

- runscripts/jenkins/Jenkinsfile/anaerobic
- runscripts/jenkins/Jenkinsfile/glucose
- runscripts/jenkins/Jenkinsfile/optional
- runscripts/jenkins/Jenkinsfile/with_aas
- runscripts/workflow.py
Fixes the logic that forwards the output of SLURM jobs submitted by `workflow.py` to the stdout of the `workflow.py` process. This functionality mainly exists to allow Jenkins to build containers and run Nextflow processes in separate SLURM jobs (Jenkins job only has 1 CPU and 4GB RAM) while still publishing their stdout/stderr. With the updated logic, the forwarded output should now be within about a minute of real-time, which is good enough for our use case. 
Additionally, this removes the unnecessary `and counting` suffix from Jenkins Slack notifications.
> Fix SLURM job output forwarding

- doc/gcloud.rst
- runscripts/nextflow/analysis.nf
- runscripts/nextflow/colony.nf
- runscripts/nextflow/config.template
- runscripts/nextflow/sim.nf
- runscripts/nextflow/template.nf
To debug a failing task on Google Cloud, the necessary files must first be symlinked into the current directory using the `.command.run` wrapper script for the task.
Additionally, this PR updates the Nextflow jobs to properly launch all scripts with `uv`.
> Fix GCP debugging instructions

- runscripts/container/runtime/Singularity
- runscripts/nextflow/analysis.nf
- runscripts/nextflow/colony.nf
- runscripts/nextflow/config.template
- runscripts/nextflow/sim.nf
- runscripts/nextflow/template.nf
- runscripts/workflow.py
Changing the Nextflow jobs to invoke `uv` instead of `python` (https://github.com/CovertLab/vEcoli/commit/95e4bd66740d63358cb33c295b7e26b8f4f1b1a5) broke containerized workflows because the container file system is read-only (`uv` tries to do an editable install of the project). Since we set the `PATH` variable to include the `uv` virtual environment in our container images and Nextflow jobs inherit the environment of the calling process, using `python` directly is fine.
Also, only use the lab's Sherlock partition for the Nextflow head job as it is the only job that requires the extended runtime limit and protection from preemption. This will likely lead to longer queue times, but this is greatly mitigated by HyperQueue and prevents one workflow from occupying all the cores available on …
> Go back to calling python instead of uv in workflow jobs

- .github/workflows/pip_audit.yml
The `--with` option for `uv` does not work the way I thought it did and creates a virtual environment that includes only `pip-audit` and its dependencies, ignoring all the dependencies for vEcoli. This PR should fix that by explicitly generating a `requirements.txt` with all vEcoli dependencies for `pip-audit` to audit.
> Fix pip-audit GitHub Action

- runscripts/container/cloud_build.json
- runscripts/container/interactive.sh
I forgot to actually set up build caching and add the necessary options for development containers on Google Cloud, as described in #296.
Setting up caching required some finesse because the [Google Cloud Build documentation](https://cloud.google.com/build/docs/optimize-builds/speeding-up-builds) is woefully out of date and, as it turns out, so is their Docker image. I had to change to the official Docker image and add a `--cache-to` argument in addition to the documented `--cache-from`, whose syntax is also different than described. For the record, none of the LLMs in Copilot were of any help in figuring this out.
Also, I added a flag to always pull from Artifact Registry before running to make sure we are using the latest version of an image. Finally, images will now be tagged with the …
> Tying up loose ends for Google Cloud containers

- .github/workflows/pip_audit.yml
- doc/experiments.rst
- doc/output.rst
- doc/workflows.rst
- runscripts/workflow.py
- More robust logic for checking the status of a job on SLURM
- Fix the pip-audit GitHub Action once and for all (also run on every PR and change to `master`)
- Document an important caveat involving nan/inf values
- Set a hard 24 hour limit on Jenkins tests
- Current Jenkins jobs all set custom timeouts lower than this hard limit (see Jenkinsfiles at `runscripts/jenkins/Jenkinsfile`)
> Minor fixes

- ecoli/processes/polypeptide_elongation.py
This PR is a small bug fix. Previously, if running with ppGpp growth-rate control turned off (e.g. if running using the MetabolismReduxClassic process), the BaseElongationModel in the process PolypeptideElongation is used. Then there was a bug for a listener that should be an int but is set to a double, resulting in parquet output files not being saved and returning an error at _finalize in parquet_emitter.py. Now the bug is fixed and the parquet files can be saved (branch being called fix-units-bug is a misnomer, sorry!).
> Fix datatype bug to allow parquet file saving with ppGpp growth-rate control turned off

- .github/workflows/pip_audit.yml
- ecoli/library/initial_conditions.py
- ecoli/processes/chromosome_structure.py
- ecoli/processes/metabolism_redux.py
- ecoli/processes/polypeptide_elongation.py
- reconstruction/ecoli/scripts/nca/nca.py
- uv.lock
I did not realize that adding the `--fix` flag silences the error code from pip-audit. Turns out there was a vulnerability in h11 that was being hidden as a result:
|Name|Version|ID|Fix Versions|
|---------|-----------|---|-----------------|
|h11|0.14.0|GHSA-vqfr-h8mv-ghfj|0.16.0|
I went ahead and updated all dependency versions while I was at it.
> pip-audit should raise error if vulnerability found

- .github/workflows/pip_audit.yml
#307 had a bug in the handling of the case where there are no security updates. This also cleans up some unnecessary code from that PR.
> Handle case of no security updates

- ecoli/analysis/multiseed/protein_counts_validation.py
- ecoli/analysis/multiseed/ribosome_spacing.py
- ecoli/analysis/multivariant/doubling_time_hist.py
- ecoli/analysis/multivariant/doubling_time_line.py
- ecoli/analysis/multivariant/new_gene_translation_efficiency_heatmaps.py
- ecoli/composites/ecoli_configs/default.json
- ecoli/composites/ecoli_master_tests.py
- ecoli/library/parquet_emitter.py
- ecoli/processes/polypeptide_initiation.py
- ecoli/variants/new_gene_internal_shift.py
- reconstruction/ecoli/flat/adjustments/rna_expression_adjustments.tsv
- reconstruction/ecoli/flat/adjustments/translation_efficiencies_adjustments.tsv
- reconstruction/ecoli/flat/new_gene_data/gfp/genes.tsv
- reconstruction/ecoli/knowledge_base_raw.py
- runscripts/analysis.py
- runscripts/create_variants.py
- runscripts/jenkins/configs/ecoli-anaerobic.json
- runscripts/jenkins/configs/ecoli-glucose-minimal.json
- runscripts/jenkins/configs/ecoli-new-gene-gfp.json
- runscripts/jenkins/configs/ecoli-no-growth-rate-control.json
- runscripts/jenkins/configs/ecoli-no-operons.json
- runscripts/jenkins/configs/ecoli-superhelical-density.json
- runscripts/jenkins/configs/ecoli-with-aa.json
- wholecell/tests/utils/profile_polymerize.py
New analyses
- Protein counts validation
- Doubling time histogram
- Ribosome spacing on mRNAs
Analyses updated/fixed
- Doubling time line
- New gene heat maps
Modeling changes
- Make new gene coordinates 1-indexed
- Use same units (codons or amino acids) for ribosome footprint and ribosome elongation rate
Bug fixes
- Fix anti join in `read_stacked_columns` (bug I introduced in f823d77)
- Do not mutate input columns to `read_stacked_column` (bug I introduced in f823d77)
- Allow users to set # CPUs in JSON for analyses
- In DuckDB helper functions, set row to 0 if dividing by 0 (`stddev` cannot handle `nan`/`inf`)
- Correctly handle integer indices in `ndidx_to_duckdb_expr`
- Move polymerize profiling monkey-patch under `if __name__ == '__main__'` to avoid running in pytest
> Add some analyses and tweak new gene module

- ecoli/experiments/ecoli_engine_process.py
- ecoli/experiments/ecoli_master_sim.py
The container images we build have neither git nor the `.git` folder. Instead the Git hash and diff of the repo are saved to the `IMAGE_GIT_HASH` environment variable and `source-info/git_diff.txt` file, respectively.
> Robust retrieval of git hash and diff metadata in containers

- pyproject.toml
- uv.lock
This PR bumps the pinned versions of all required packages to the latest available.
Additionally, it downgrades ortools in order to upgrade protobuf to 6.31.1 (supersedes #326).
The large diff is because this also updates `uv.lock` to revision 2 of the file format.
> Python dependency updates

- .github/workflows/docker_security.yml
- README.md
- doc/gcloud.rst
- ecoli/experiments/ecoli_master_sim.py
- ecoli/library/parquet_emitter.py
- ecoli/library/test_parquet_emitter.py
- ecoli/processes/engine_process.py
- runscripts/container/Dockerfile
- runscripts/container/Singularity
- runscripts/sim.py
- runscripts/workflow.py
Addresses some issues with deploying on Google Cloud that cropped up since I last tested it.
- Streamline setup process with more explicit instructions
- Explicitly install `curl` to fix authentication via the metadata server on Compute Engine
- Implement more robust output overwrite protection and fix typo in `runscripts/workflow.py`
- Explicitly call `ecoli.library.parquet_emitter.ParquetEmitter.finalize()` in `try...finally` block to write remaining buffered emits if exception is raised. This gets around some limitations of the previous `atexit` hook approach. For one, exceptions raised in `atexit` hooks were ignored and not reflected in the final exit code. When the hook failed in a Nextflow workflow, the user would get no indication of this unless they manually checked the stderr. …
> Google Cloud Fixes

- ecoli/analysis/multigeneration/ribosome_usage.py
- ecoli/analysis/multivariant/cell_mass.py
Plot absolue / normalized cell mass over time for `multivariant` simulation in vEcoli, and:
1. each variant has its own plot;
2. at each subplot, time is divided by `generation id`;
It can also be used at multigeneration analysis.
> Add cell_mass analysis used for multivariant simulation

- doc/hpc.rst
The binary resulting from `nextflow self-update` has 711 permissions, which prevents other lab members on Sherlock from using it.
> Reminder to set shared binary permissions after updating
